spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dentist_archive_db
    username: postgres
    password: user1234

server:
  port: 8087
app:
  delays-after-failed-login-attempts-for-users:
    - number-of-fails: 3
      delay: 1m
    - number-of-fails: 5
      delay: 5m
    - number-of-fails: 10
      delay: 1h

auth-server:
  user-access-token-life-time: 30M
  session-max-inactive-time: 30D
  jwk:
    keys:
      - key-id: 2b3fee3d-b382-4346-b6e8-ae3f9e19fc3e
        private-key-path: classpath:/data/local/keys/id_ecdsa.pem
        public-key-path: classpath:/data/local/keys/id_ecdsa_pub.pem
